version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./agents.db
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-default-secret-key}
    volumes:
      - ./backend:/app
      - agent_data:/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - agent_network

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - BACKEND_URL=http://backend:8000
    volumes:
      - ./frontend:/app
    command: chainlit run app.py --host 0.0.0.0 --port 8001
    depends_on:
      - backend
    networks:
      - agent_network

  # Optional: PostgreSQL for production
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: agents
  #     POSTGRES_USER: agent_user
  #     POSTGRES_PASSWORD: agent_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - agent_network

volumes:
  agent_data:
  # postgres_data:

networks:
  agent_network:
    driver: bridge
